### ISSUE TITLE
域名绑定问题

### ISSUE THREAD

**Issue by xhemj** [js-cool/js.cool#11]
我想把域名绑定在Vercel上，但它提示无法绑定，已经有其他的人绑定了？
![IMG_20201008_115646.jpg](https://i.loli.net/2020/10/08/9DjIBwPvN5srldq.jpg)

**Comment by willin** [comment]
你可以尝试一下任意的二级域名，比如 `asdf123123123dsfa.js.cool`， 理论上来说是没有任何添加限制的。
可能真的是被绑定过了，如果不是你，那就是其他人。

**Comment by willin** [comment]
而且。。。  

`*.now.sh` 应该应该已经过时了吧，应该是用 `*.vercel.app`

**Comment by xhemj** [comment]
*.now.sh是可以用的
任意的二级域名也不行，直接被提醒没有权限

**Comment by willin** [comment]
vercel 添加过一个二级域名之后就不能再添加了。。。貌似是这样。

**Comment by willin** [comment]
有没有其他平台可以部署

**Comment by xhemj** [comment]
那就换到Coding上吧，我已经重新开了一个pr了

**Comment by xhemj** [comment]
#12

**Comment by willin** [comment]
ok
