### ISSUE TITLE
支持威廉王巨佬！

### ISSUE THREAD

**Issue by heson525** [js-cool/js.cool#17]
看到老威廉， 就忍不住就发个支持issue！项目很好，支持！

**Comment by willin** [comment]
你的名字看着很眼熟啊。。

**Comment by heson525** [comment]
> 你的名字看着很眼熟啊。。

呀，好久好久以前，大概十年前，玩wp情侣博客的那个heson 。当时经常去你博客逛，wp邮件回复插件巨好用！😂

**Comment by willin** [comment]
啊噢  yy&heson

**Comment by heson525** [comment]
大佬记性真好😄

**Comment by willin** [comment]
王叨叨，林木木，张三，荒野无灯。。。。。。
一晃多年
