### ISSUE TITLE
请求！！！

### ISSUE THREAD

**Issue by zwtdzh** [js-cool/js.cool#26]
您好！我可以帮你弄那个网站源码哦！另外我也想加入你们团队！

**Comment by willin** [comment]
哪个网站？

**Comment by zwtdzh** [comment]
js-cool.github.io这个

**Comment by zwtdzh** [comment]
https://js.cool/这个

**Comment by willin** [comment]
您可以 Fork 该项目，然后提交 PR。目前工作繁忙，没有精力做这个事情。

**Comment by zwtdzh** [comment]
哦我先把源码写好在给你发过去吧

**Comment by willin** [comment]
🆗

**Comment by zwtdzh** [comment]
您的域名有备案号吗？我在网站里可以加入！

**Comment by zwtdzh** [comment]
http://zwtdwz.js.cool/ymff.html
这是一个最简单的首页模板您要加入其他什么功能吗比如统计啥的！

**Comment by zwtdzh** [comment]
其他风格还有19套不同的！

**Comment by willin** [comment]
wc 被注销了

**Comment by zwtdzh** [comment]
注销了！！！

**Comment by zwtdzh** [comment]
注销了？？？为啥？

**Comment by willin** [comment]
不知道，可能新顶级后缀原因吧

**Comment by zwtdzh** [comment]
哦哦

**Comment by zwtdzh** [comment]
我找到了很久以前我编写的一个官网哈哈你看看是不是很好看
http://zwtdwz.js.cool/

**Comment by willin** [comment]
好看是好看。

我期望的是这样： 

- 单页应用，通过 nuxt + stylus 进行扩展
- 轻，原生（Vanilla JS），不用 jQuery 等库
- 支持浅、深模式

**Comment by zwtdzh** [comment]
ok好的

**Comment by willin** [comment]
欢迎再次提交
