### ISSUE TITLE
您好请问下，可以默认是https的吗

### ISSUE THREAD

**Issue by wangdabaoqq** [js-cool/js.cool#40]
如题

**Comment by willin** [comment]
默认 cloudflare ssl

**Comment by wangdabaoqq** [comment]
@willin 我这里需要配置什么规则吗，你说`默认 cloudflare ssl`但是为什么我访问的时候走的还是http。

**Comment by willin** [comment]
![QQ20210514-114055](https://user-images.githubusercontent.com/1890238/118218054-44b33500-b4a9-11eb-910a-c2713e486434.png)

你把这个勾上 我给你重新配置一下

**Comment by willin** [comment]
你的两个项目都需要设置一下，我把 cf 的 ssl 关了

**Comment by wangdabaoqq** [comment]
@willin 我看了这里，我不能勾选。

**Comment by willin** [comment]
过一阵子再看
10分钟这样

**Comment by wangdabaoqq** [comment]
好的。麻烦您了

**Comment by wangdabaoqq** [comment]
@willin 我已经勾选了，访问地址也是强制https了。
谢谢您。

**Comment by wangdabaoqq** [comment]
@willin `wangdabao.js.cool`这个域名的证书显示不安全。

**Comment by wangdabaoqq** [comment]
可以了，问题解决了。
