### ISSUE TITLE
txt records for atordvairn.js.cool

### ISSUE THREAD

**Issue by atordvairn** [js-cool/js.cool#58]
Thanks for this amazing service
Can you please add the below txt record for `atordvairn.js.cool`

google-site-verification=osdbHnH4vU-pBcbLFUbQFjgtcD-URHHAyLQZhP-l9YM

**Comment by willin** [comment]
done

**Comment by atordvairn** [comment]
![Screenshot_2022-01-10-10-13-10-856](https://user-images.githubusercontent.com/97218417/148720919-ba651672-fd31-4fd7-bb7b-55925ebef54a.jpeg)
Thanks!!!
